### ISSUE TITLE
zsh compinit: insecure files, run compaudit for list.?

### ISSUE THREAD

**Issue by frzyq** [zsh-users/zsh-completions#671] opened 2019-12-09 16:39 UTC
zsh compinit: insecure files, run compaudit for list.
Ignore insecure files and continue [y] or abort compinit [n]? y%

Execute the compaudit command to get the following file path：

here are insecure files:
/usr/local/share/zsh/site-functions/_brew_services
/usr/local/share/zsh/site-functions/_carthage

How can I solve it?   thank！

**Comment by MaximDevoir** [comment] 2020-02-19 05:22
From [#680](https://github.com/zsh-users/zsh-completions/issues/680#issuecomment-588003627)

> For security reasons compinit also checks if the completion system would use **files not owned by root or by the current user**, or **files in directories that are world- or group-writable or that are not owned by root or by the current user**. If such files or directories are found, compinit will ask if the completion system should really be used. To avoid these tests and make all files found be used without asking, use the option -u, and to make compinit silently ignore all insecure files and directories use the option -i. This security check is skipped entirely when the -C option is given.

> zsh thinks potentially dangerous files could be loaded and is, therefore, taking steps to try and prevent that. 

This question may be a duplicate of #433, #680, and ohmyzsh/ohmyzsh#6835 - check these out for a possible solution. Generally, fixing the issue means changing the permissions or group settings for insecure files, or by setting `ZSH_DISABLE_COMPFIX` to `"true"` in your `.zshrc` file.

**Closed** 2020-02-19 05:53 UTC
Labels: Question, Upstream
