### ISSUE TITLE
Yarn v2 workspace autocomplete not working

### ISSUE THREAD

**Issue by phuctm97** [zsh-users/zsh-completions#802] opened 2021-05-22 06:02 UTC
I'm using yarn v2 and looks like workspace auto-completion is not working correctly. Any idea on how can it be solved, would love to contribute if possible!

Thank you.

**Comment by phuctm97** [comment] 2021-05-22 06:04
Just went a little into it, it is caused by: `yarn workspaces info` is not valid in Yarn v2, instead it's `yarn workspace list --json`, the output is a bit different, too.

**Comment by kachkaev** [comment] 2021-12-06 15:19
@phuctm97 have you found any solution for Yarn 2/3? Just wonder if there is any other source of autocompletions.

Seems like the problem is not only related to workspaces. After I have migrated https://github.com/kachkaev/njt and https://github.com/kachkaev/suppress-exit-code to Yarn Berry, I am no longer seeing suggestions for `package.json` scripts in both projects. I.e. when I type `yarn fi [tab]`, it does not turn into `yarn fix`. Path autocompletion is also lost: `yarn test sr [tab]` does not become `yarn test src/`.

Interestingly, autocompletion for default commands still works, i.e. `yarn ini [tab]` becomes `yarn init`.

**Comment by syohex** [comment] 2021-12-07 14:13
Sorry very late reply. I'm not sure, is https://github.com/zsh-users/zsh-completions/pull/827 ok ?

![yarn](https://user-images.githubusercontent.com/554281/145044796-1435f5be-f6cd-47f0-9439-ae50b551ca30.gif)

**Comment by syohex** [comment] 2021-12-11 03:28
I have merged #827. Please check latest version and close this issue if you have no problems,

**Closed** 2021-12-21 23:41 UTC
Labels: Bug

**Comment by kachkaev** [comment] 2022-02-17 19:10
Thanks @syohex and sorry for a slow reply. Workspace autocompletion seems to work for me both with Yarn 1 and 3 👍 Just got the most recent version on a new laptop and could finally test it. Great stuff!
